#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#lists:
##  type      : rest
##  resource  : App\Controller\ListController
##  prefix    : lists

#users:
#  type      : rest
#  resource  : App\Controller\UsersController
#  prefix    : api/users
